name: cfdna_mk Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
      - bioinformatics/cfdna_mk.dockerfile
      - bioinformatics/cfdna_mk_requirements.txt
      - bioinformatics/cfdna_mk_install_packages.R
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Build the cfdna_mk's Docker image
      run: docker build --file bioinformatics/cfdna_mk.dockerfile -t ${{secrets.DOCKER_USER}}/cfdna_mk:$(date +'%Y-%m-%d') -t ${{secrets.DOCKER_USER}}/cfdna_mk:latest .
      # $(date +%s)
    - name: Docker Push
      run: docker push -a ${{secrets.DOCKER_USER}}/cfdna_mk
